### ISSUE TITLE
内容获取方式的疑问

### ISSUE THREAD

**Issue by ruibaby** [HandsomeNPC/halo-wangEditor-plugin#1]
通过源码可以看到，目前内容是通过在挂载组件之后调用接口获取的：

https://github.com/HandsomeNPC/halo-wangEditor-plugin/blob/87a4424db98ac5cd17739cb7fc1d3d4262b1d164/console/src/components/wangEditor.vue#L74-L86

但其实在 Halo 的扩展点实现中，编辑器组件已经提供了 raw 和 content 的 props，可以直接使用，可参考文档：https://github.com/halo-dev/halo/blob/main/console/docs/extension-points/editor.md

可以考虑优化一下。

**Comment by HandsomeNPC** [comment]
> 通过源码可以看到，目前内容是通过在挂载组件之后调用接口获取的：
> 
> https://github.com/HandsomeNPC/halo-wangEditor-plugin/blob/87a4424db98ac5cd17739cb7fc1d3d4262b1d164/console/src/components/wangEditor.vue#L74-L86
> 
> 但其实在 Halo 的扩展点实现中，编辑器组件已经提供了 raw 和 content 的 props，可以直接使用，可参考文档：https://github.com/halo-dev/halo/blob/main/console/docs/extension-points/editor.md
> 
> 可以考虑优化一下。

好的，我研究一下

**Comment by HandsomeNPC** [comment]
> 通过源码可以看到，目前内容是通过在挂载组件之后调用接口获取的：
> 
> https://github.com/HandsomeNPC/halo-wangEditor-plugin/blob/87a4424db98ac5cd17739cb7fc1d3d4262b1d164/console/src/components/wangEditor.vue#L74-L86
> 
> 但其实在 Halo 的扩展点实现中，编辑器组件已经提供了 raw 和 content 的 props，可以直接使用，可参考文档：https://github.com/halo-dev/halo/blob/main/console/docs/extension-points/editor.md
> 
> 可以考虑优化一下。

参考你的文档,我把获取内容的代码修改为通过组件获取,把原来调用接口的代码删掉了

**Comment by ruibaby** [comment]
Close in https://github.com/HandsomeNPC/halo-wangEditor-plugin/commit/40d8ac24582325aae920cc844647b9e0f5f981cb
