### ISSUE TITLE
使用此编辑器之后，页面 crash

### ISSUE THREAD

**Issue by ruibaby** [HandsomeNPC/halo-wangEditor-plugin#2]
日志：

<img width="571" alt="image" src="https://user-images.githubusercontent.com/21301288/236751473-c72ce7a8-6c55-4abd-8721-b18ba6ae06b3.png">

**Comment by HandsomeNPC** [comment]
这个错误是怎么操作出来的,我复现一下看看

**Comment by ruibaby** [comment]
新建文章，切换到 wangEditor。

**Comment by HandsomeNPC** [comment]
> 新建文章，切换到 wangEditor。

我在电脑上新建文章，切换到wangEditor没有看到你报的这个错误呀
![image](https://user-images.githubusercontent.com/117186834/236840899-725c4406-fece-451e-bbd5-e490d5fb0541.png)

**Comment by ruibaby** [comment]
> 我在电脑上新建文章，切换到wangEditor没有看到你报的这个错误呀

可能和我本地的环境或者数据有关，但我似乎在 https://github.com/HandsomeNPC/halo-wangEditor-plugin/pull/3 中已经修复，有时间请帮忙 Review 一下。
