### ISSUE TITLE
下载后无法build

### ISSUE THREAD

**Issue by 125835373** [HandsomeNPC/halo-wangEditor-plugin#5]
下载后无法bulid，可否将bulid后的jar包直接上传至仓库种，方便下载

**Comment by HandsomeNPC** [comment]
下载完代码以后执行./gradlew build就可以完成打包呀,jar包在右侧的RELEASE中可以下载
![image](https://github.com/HandsomeNPC/halo-wangEditor-plugin/assets/117186834/51b2fd67-abe4-4a1d-b9a2-da21d998f35e)
